package com.miaoshaproject.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.id
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promo_name
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    private String promoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.start_date
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.item_id
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promo_price
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    private Double promoPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.id
     *
     * @return the value of promo_info.id
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.id
     *
     * @param id the value for promo_info.id
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promo_name
     *
     * @return the value of promo_info.promo_name
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promo_name
     *
     * @param promoName the value for promo_info.promo_name
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.start_date
     *
     * @return the value of promo_info.start_date
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.start_date
     *
     * @param startDate the value for promo_info.start_date
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.item_id
     *
     * @return the value of promo_info.item_id
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.item_id
     *
     * @param itemId the value for promo_info.item_id
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promo_price
     *
     * @return the value of promo_info.promo_price
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public Double getPromoPrice() {
        return promoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promo_price
     *
     * @param promoPrice the value for promo_info.promo_price
     *
     * @mbggenerated Sun Apr 07 15:39:37 CST 2019
     */
    public void setPromoPrice(Double promoPrice) {
        this.promoPrice = promoPrice;
    }
}